apiVersion: v1
kind: ConfigMap
metadata:
  name: carbon-coach-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "4000"
  JWT_SECRET: "carbon-secret-key-12345"
  JWT_REFRESH_SECRET: "carbon-refresh-secret-12345"
  DATABASE_URL: "postgresql://carbon_user:carbon_pass@postgres-service:5432/carbon_db?schema=public"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
