apiVersion: v1
kind: Service
metadata:
  name: carbon-coach-backend-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: carbon-coach-backend
